### ISSUE TITLE
The rise endpoint not working as expected

### ISSUE THREAD

**Issue by Hephaest** [ko28/melon-api#26]
Dear @ko28 @hdko,

Thanks for your work! I have found the list from the rise endpoint is absolutely obsoleted, so I browsed the [link](https://www.melon.com/chart/rise/index.htm). I am not a native speaker, but this shows that Melon turns off the rising ranking service (Despite the crawler finding the hidden elements, the result is completely incorrect).

### Source Code
```html
<div id="tb_list" style="display: none">
<!---// table details>
<div>
```

### Screenshot
<img width="600" alt="Melon Bug" src="https://user-images.githubusercontent.com/37981444/129482517-cd5b6669-92b1-4fd8-a827-12aa8bc840bf.png">

**Comment by ko28** [comment]
Thanks for pointing this out! I'll deprecate the rise endpoint. :smile:

**Comment by ko28** [comment]
closed via https://github.com/ko28/melon-api/commit/ba16e4e9ad6d4ba079ae6a2c32a40ae14de738b5
